- go.mod
- go.sum
- tpl/hertz/standard/package.yaml
fix
en:  fix the problem for hertz template
zh: 修复 hertz 模板定义类型的改变
> fix: modify hertz template

- cmd/static/client_flags.go
- cmd/static/server_flags.go
- config/server.go
- pkg/client/check.go
- pkg/client/kitex.go
- pkg/common/kx_registry/registry.go
- pkg/server/check.go
- pkg/server/kitex.go
fix
en: module not work outside gopath
zh: 在 gopath 外指定 module 参数不生效
> fix: module not specified outside gopath

- cmd/dynamic/common.go
fix
en: Prompt `could not find matching module` after inputting module in dynamic command line
zh: 动态命令行输入 module 后提示 `could not find matching module`
#27
> fix: dynamic terminal module cannot bind

- go.mod
- go.sum
- pkg/server/hz.go
- tpl/init.go
feat
en: add windows support
1. use `os.TempDir` to decide temp dir
2. switch some hertz option's separator from `:` to `|` to avoid conflicts with `C:` in the windows path
zh: 增加 windows 支持
1. 用 `os.TempDir` 去决定 temp dir 的位置
2. 将 hertz 一些选项的分隔符从 `:` 切换到 `|` 以避免与 windows 路径中的 `C:` 冲突
> feat: add windows support

- pkg/client/hz.go
feat
en: 
zh: 增加 `--pass` 参数中的 `hz` 的 `--client_dir` 选项
> feat(client): add hz  --client_dir option in --pass

- docs/terminal.md
> docs: update terminal.md

- docs/layout.md
docs
en: update doc url in layout.md
zh: 更新 layout.md 中的文档链接
> docs: update docs layout.md

- cmd/dynamic/cmd_test.go
- go.mod
test
en: add dynamic cmd test
zh: 增加动态命令行测试
> test: add dynamic cmd test

- README.md
- README_EN.md
> docs: add README_EN.md

- README.md
docs
en: use more accurate descriptions
zh: 使用更加准确的描述
> docs: use more accurate descriptions

- pkg/client/hz.go
fix
en: protobuf lose out dir for hz
zh: protobuf 缺失 "out_dir" 参数，导致生成protobuf失败
https://github.com/cloudwego/cwgo/issues/53
> fix: protobuf lose out dir for hz

- tpl/hertz/standard/layout.yaml
- tpl/kitex/server/standard/conf_dev_tpl.yaml
- tpl/kitex/server/standard/conf_online_tpl.yaml
- tpl/kitex/server/standard/conf_test_tpl.yaml
- tpl/kitex/server/standard/conf_tpl.yaml
- tpl/kitex/server/standard/redis.yaml
en:  redis to v9, add redis username db config，online default disable pprof.
zh:  redis升级到v9，增加redis用户db配置，online配置禁用pprof。
> chore: Modify template

- tpl/hertz/standard/layout.yaml
fix
en:  adjust the registration order of middleware
zh: 调整中间件的注册顺序在路由注册之前
> fix: adjust the registration order of middleware

- tpl/hertz/standard/layout.yaml
optimize
en: modify init hlog order，avoid loss of log printing for registered routes
zh: 调整初始化 hlog 的顺序，避免丢失注册路由的日志
> optimize: modify init hlog order

- go.mod
- go.sum
> chore: upgrage kitex version

- pkg/client/kitex.go
- pkg/server/kitex.go
fix
en: add kitexArgument.ProtobufPlugins
zh: 添加 ProtobufPlugins
> fix: add kitexArgument.ProtobufPlugins

- tpl/kitex/server/standard/kitex_yaml.yaml
🐞 fix: fix bug missing closing quota  in kitex_info.yaml file.
en: Resolve the error in the kitex_info.yaml file.
zh: 解决生成代码中 kitex_info.yaml 文件中的错误。
Fixes #72
> 🐞 fix: fix bug missing closing quota  in kitex_info.yaml

- go.mod
- go.sum
> chore: update hz version

- pkg/server/hz.go
feat
en: 
zh: 支持用户自定义 render.json 文件
> feat: support user-defined render.json

- pkg/client/check.go
- pkg/client/client.go
- pkg/client/kitex.go
- pkg/common/utils/env.go
- pkg/common/utils/git.go
- pkg/common/utils/hz.go
- pkg/common/utils/slice.go
- pkg/consts/const.go
- pkg/server/kitex.go
- pkg/server/server.go
fix
en: 
zh: 修复 client 在 windows 下的 bug；复用 ReplaceThriftVersion 函数；修改部分常量
> fix: client windows bug && reuse code && consts

- cmd/static/cmd.go
- example/hex/conf/dev/conf.yaml
- example/hex/conf/online/conf.yaml
- example/hex/conf/test/conf.yaml
- tpl/hertz/server/standard/layout.yaml
- tpl/kitex/server/standard/conf_dev_tpl.yaml
- tpl/kitex/server/standard/conf_online_tpl.yaml
- tpl/kitex/server/standard/conf_test_tpl.yaml
> chore: gorm mysql dsn default utf8mb4

- pkg/server/server.go
optimize
en: Add prompt messages after existing go.mod
zh:现有go.mod条件下添加提示消息
> optimize: Adding prompt messages under existing go.mod conditions

- pkg/client/client.go
- pkg/common/utils/env.go
- pkg/server/server.go
feat
en: feat: support pb gomod lock thrift version
zh: pb 类型的 idl gomod 文件中也自动锁定 thrift 的版本
> feat: support pb gomod lock thrift version

- tpl/kitex/client/standard/client_tpl.yaml
- tpl/kitex/client/standard/default_tpl.yaml
- tpl/kitex/client/standard/init_tpl.yaml
en:  fix(kitex): update client template
zh: 更新 kitex client 模板
> fix(kitex): update client template

- tpl/hertz/server/standard/layout.yaml
- tpl/kitex/server/standard/main_tpl.yaml
en:  default async log
zh: 默认使用异步日志
Fixes #108
> feat: default async log

- tpl/hertz/server/standard/package.yaml
- tpl/kitex/server/standard/service_test.yaml
feat
en: optimize unit_test template
zh:优化了单测模版
> feat:optimize unit_test template

- example/hex/biz/dal/redis/init.go
- example/hex/biz/service/hello_method.go
- example/hex/biz/service/hello_method_test.go
- example/hex/handler.go
- example/hex/hex_trans_handler.go
- example/hex/main.go
- tpl/kitex/server/standard/service.yaml
- tpl/kitex/server/standard/service_test.yaml
fix
en:  fix: fix service.go tpl in kitex server
zh: 修复 kitex server 的 service.go 和 service_test.go 的模板
#121
> fix: fix service.go tpl in kitex server

- platform/manifest/deploy/docker/.dockerignore
fix
我使用的是 darwin 平台, 拥有开发前端页面的 node_module 文件jia, 其中 esbuild 版本为 darwin
与执行 *RUN pnpm i* 所需的 linux 版本的 esbuild 有冲突. 
将 node_module 添加进入 .dockerignore, 防止复用导致的冲突
> fix(docker): add .dockerignore file

- platform/server/shared/repository/manager.go
fix
en: add repo for github bug
zh:
> fix(platform): add repo for github bug

- platform/web/src/pages/IdlPage/index.tsx
- platform/web/src/utils/consts.ts
fix
en: 
zh: 修正无法正确查看 import idls 的 bug
> fix(platform-front): cannot open correct repo url for import idls

- pkg/common/utils/git.go
feat
en: support ssh gitURL && more error log detail
zh:
#138
> feat: support ssh gitURL && more error log detail

- cwgo.go
- tpl/init.go
fix
en: add template func
zh: 添加模版函数
> fix: add template func

- go.sum
- pkg/consts/const.go
- pkg/server/kitex.go
feat
en: support hex protobuf
zh: 支持 hex protobuf
> feat: hex protobuf

- go.mod
- go.sum
> chore: update kitex version

- pkg/server/kitex.go
fix 
en:  shield short connection error for hex
zh: 屏蔽 hex 的底层短连接错误
> fix: shield short connection error for hex

- .github/workflows/pr-check.yml
- README.md
- README_CN.md
- cmd/static/cmd.go
- pkg/consts/const.go
> feat: auto gen completion script

- pkg/client/client.go
- pkg/common/utils/env.go
- pkg/server/server.go
> fix: add hessian2 post processing

- go.mod
- go.sum
> fix: downgrade google.golang.org/protobuf version

- meta/version.go
> chore: update cwgo version to v0.1.0

- cmd/static/cmd.go
- pkg/client/client.go
- pkg/common/utils/env.go
- pkg/server/server.go
en: 
zh: 更新 golang protobuf 版本
> chore: upgrade google protobuf

- cmd/static/client_flags.go
- cmd/static/server_flags.go
- config/client.go
- config/server.go
- pkg/client/hz.go
- pkg/client/kitex.go
- pkg/common/utils/git.go
- pkg/consts/const.go
- pkg/server/hz.go
- pkg/server/kitex.go
en:  feat: support git clone template repo branch
zh:
> feat: support git clone template repo branch

- go.mod
- go.sum
chore: dependency upgrade
en: upgrade sonic
zh:
#173
> chore: dependency upgrade

- pkg/curd/parse/query.go
en:  fix: mongo doc query conditions parse error
zh:
> fix: mongo doc query conditions parse error

- tpl/hertz/server/standard/layout.yaml
- tpl/hertz/server/standard_v2/layout.yaml
- tpl/kitex/server/standard/conf_tpl.yaml
en: 
zh: hertz 增加一个 servicename，删除 kitex 配置结构体中无用的部分
> chore: add service name for hertz and remove kitex unused config

- pkg/model/model.go
en: 
zh:
https://github.com/cloudwego/cwgo/issues/199
> fix: add type tag for gen

- meta/version.go
> chore: update version v0.1.2

- go.mod
- tpl/hertz/server/standard/layout.yaml
- tpl/hertz/server/standard_v2/layout.yaml
- tpl/kitex/server/standard/conf_tpl.yaml
> chore: update gopkg.in/yaml v2 to v3
